global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'account-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['account-api:8080']
        labels:
          application: 'Account-API'
  - job_name: 'transaction-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['transaction-api:8080']
        labels:
          application: 'Transaction-API'
  - job_name: 'asset-management-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['asset-management-api:8080']
        labels:
          application: 'Asset-management-API'
  - job_name: 'notification-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-api:8080']
        labels:
          application: 'Notification-API'
  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8761']
        labels:
          application: 'Discovery-Server'
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['config-server:8888']
        labels:
          application: 'Config-Server'
